worker-threads: 4
worker-fs-threads: 2
logger-level: info

is-testing: false

server-port: 8080

dbconnection: 'postgresql://pg_service_template_user:password@localhost:5432/pg_service_template_db_1'

secdist-path: /configs/secure_data.json

server-name: sample-production-service 1.0
service-name: sample-production-service
 
config-server-url: http://localhost:8083/
monitor-server-port: 8086
 
testsuite-enabled: false
 
userver-dumps-root: /var/cache/production_service/userver-dumps/
access-log-path: /var/log/production_service/access.log
access-tskv-log-path: /var/log/production_service/access_tskv.log
default-log-path: /var/log/production_service/server.log
secdist-path: /etc/production_service/secure_data.json
 
config-cache: /var/cache/production_service/config_cache.json