components_manager:
    task_processors:                  # Task processor is an executor for coroutine tasks

        main-task-processor:          # Make a task processor for CPU-bound couroutine tasks.
            worker_threads: $worker-threads         # Process tasks in 4 threads.

        fs-task-processor:            # Make a separate task processor for filesystem bound tasks.
            worker_threads: $worker-fs-threads

        monitor-task-processor:  # for monitoring
            thread_name: mon-worker
            worker_threads: $monitor_worker_threads
            worker_threads#fallback: 1

    default_task_processor: main-task-processor

    components:                       # Configuring components that were registered via component_list
        server:
            listener:                 # configuring the main listening socket...
                port: $server-port            # ...to listen on this port and...
                task_processor: main-task-processor    # ...process incoming requests on this task processor.
            listener-monitor:
                # Listen on localhost:8085 for developer/utility requests
                port: $monitor-server-port
                port#fallback: 8086
                connection:
                    in_buffer_size: 32768
                    requests_queue_size_threshold: 100
                task_processor: monitor-task-processor
        logging:
            fs-task-processor: fs-task-processor
            loggers:
                default:
                    file_path: '@stderr'
                    level: $logger-level
                    overflow_behavior: discard  # Drop logs if the system is too busy to write them down.

        dump-configurator:
            dump-root: $userver-dumps-root

        congestion-control:
            fake-mode: $testsuite-enabled
            load-enabled: true

        dynamic-config:
            updates-enabled: true
            fs-cache-path: $config-cache
            fs-task-processor: fs-task-processor

        dynamic-config-client:
            load-enabled: false
            config-url: $config-server-url
            http-retries: 5
            http-timeout: 20s
            service-name: $service-name

        dynamic-config-client-updater:
            load-enabled: false
            config-settings: false
            first-update-fail-ok: true
            full-update-interval: 1m
            store-enabled: true
            load-only-my-values: true
            update-interval: 5s

        handler-implicit-http-options:
            as_fallback: implicit-http-options
            method: OPTIONS
            task_processor: main-task-processor
            throttling_enabled: false
        
        http-client-statistics:
            fs-task-processor: fs-task-processor
            pool-statistics-disable: true
            thread-name-prefix: stats
            user-agent: $server-name
        
        logging-configurator:
            limited-logging-enable: true
            limited-logging-interval: 1s

        system-statistics-collector:
            fs-task-processor: fs-task-processor


        # Dynamic config options. Cache is disabled, updates are disabled.
        dynamic-config:
            # For most of userver dynamic configs, defaults are used, some are overridden here.
            # See userver "dynamic config" docs for what configs exist.
            defaults:
                HTTP_CLIENT_CONNECTION_POOL_SIZE: 1000
                POSTGRES_DEFAULT_COMMAND_CONTROL:
                    network_timeout_ms: 750
                    statement_timeout_ms: 500

        secdist:
            provider: default-secdist-provider
        default-secdist-provider:
            config: $secdist-path

        rate-manager:
            url_all_currencies: "https://api.currencyapi.com/v3/currencies"
            url_latest_exchange_rates: "https://api.currencyapi.com/v3/latest"

        testsuite-support: {}

        http-client:
            load-enabled: $is-testing
            fs-task-processor: fs-task-processor

        tests-control:
            load-enabled: $is-testing
            path: /tests/{action}
            method: POST
            task_processor: main-task-processor
        handler-ping:
            path: /ping
            method: GET
            task_processor: main-task-processor
            throttling_enabled: false
            url_trailing_slash: strict-match

        handler-rates:
            path: /v1/rates
            method: GET
            task_processor: main-task-processor
        
        handler-currencies:
            path: /v1/currencies
            method: GET
            task_processor: main-task-processor

        handler-update:
            path: /v1/update
            method: GET
            task_processor: main-task-processor
    
        postgres-db-1:
            dbconnection: $dbconnection
            blocking_task_processor: fs-task-processor
            dns_resolver: async
            sync-start: false
            connlimit_mode: manual

        handler-inspect-requests:
            path: /service/inspect-requests
            method: GET
            task_processor: monitor-task-processor

        handler-jemalloc:
            path: /service/jemalloc/prof/{command}
            method: POST
            task_processor: monitor-task-processor

        handler-log-level:
            path: /service/log-level/{level}
            method: GET,PUT
            task_processor: monitor-task-processor

        handler-on-log-rotate:
            path: /service/on-log-rotate/
            method: POST
            task_processor: monitor-task-processor

        handler-dynamic-debug-log:
            path: /service/log/dynamic-debug
            method: GET,PUT,DELETE
            task_processor: monitor-task-processor

        handler-dns-client-control:
            path: /service/dnsclient/{command}
            method: POST
            task_processor: monitor-task-processor

        handler-server-monitor:
            path: /service/monitor
            method: GET
            task_processor: monitor-task-processor

        handler-fired-alerts:
            path: /service/fired-alerts
            method: GET
            task_processor: monitor-task-processor

        dns-client:
            fs-task-processor: fs-task-processor
